"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const router = express.Router();
const clientController = require("./../controllers/clientController");
const auth = require("./../middleware/auth");
const checkError = require("./../helpers/checkUser");
router.post("/", auth, clientController.getById);
// router.get("/", auth, authController.me);
// router.put("/", checkError(), auth, authController.edit);
// router.delete("/", auth, authController.delete);
module.exports = router;
