"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const router = express.Router();
const policyController = require("./../controllers/policyController");
const auth = require("./../middleware/auth");
const permissions = require("../middleware/permissions");
router.post("/get-by-name", auth, permissions.adminOnly,  policyController.policiesByUsername);
router.post("/get-client-info", auth, permissions.adminOnly,  policyController.getPolicyOwner);
module.exports = router;