"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const router = express.Router();
const policyController = require("./../controllers/policyController");
const auth = require("./../middleware/auth");
const checkError = require("./../helpers/checkUser");
router.post("/get-by-name", auth, policyController.policiesByUsername);
router.post("/get-client-info", auth, policyController.getPolicyOwner);
module.exports = router;
